[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "anglo-defects"
version = "24.3.140"
requires-python = ">=3.12"
dependencies = [
  "django==4.2.6",
  "python-dotenv==1.0.0",
  "whitenoise==6.5.0",
  "gunicorn==21.2.0",
  "dj-database-url==2.1.0",
  "django-auditlog==2.3.0",
  "redis==5.0.1",
  "sentry_sdk==1.31.0",
  "django-import-export==3.3.1",
  "django-crispy-forms==2.0",
  "crispy-bootstrap5==0.7",
  "pillow==10.0.1",
  "huey==2.5.0",
  "weasyprint==60.1",
]

[project.scripts]
"manage.py" = "manage.py:main"

[project.optional-dependencies]
dev = [
  "pip-tools",
  "coverage",
]


[tool.setuptools]
packages = ["defects"]
include-package-data = true

[tool.coverage.run]
omit = [
  "*/migrations/*.py",
  "manage.py",
  "*/__init__.py",
]
