[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "anglo-defects"
version = "22.11.14"
requires-python = ">=3.10"
dependencies = [
    'django>=4.1,<4.2',
    'pytz==2022.6',
    'python-dotenv==0.21.0',
    'whitenoise==6.2.0',
    'gunicorn==20.1.0',
    'dj-database-url==1.0.0',
    'django-lifecycle==1.0.0',
    'redis==4.3.4',
    'sentry_sdk==1.10.1',
    'django-import-export==3.0.1',
    'django-crispy-forms==1.14.0',
    'crispy-bootstrap5==0.7',

]

[project.scripts]
"manage.py" = "manage.py:main"

[project.optional-dependencies]
dev = ["pip-tools"]

[tool.setuptools]
packages = ['defects']
include-package-data = true
