[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "anglo-defects"
version = "23.7.241"
requires-python = ">=3.11"
dependencies = [
  'django==4.2.4',
  'python-dotenv==1.0.0',
  'whitenoise==6.5.0',
  'gunicorn==21.2.0',
  'dj-database-url==2.0.0',
  'django-auditlog==2.3.0',
  'redis==5.0.0',
  'sentry_sdk==1.29.2',
  'django-import-export==3.2.0',
  'django-crispy-forms==2.0',
  'crispy-bootstrap5==0.7',
  'pillow==10.0.0',
  'huey==2.4.5',
]

[project.scripts]
"manage.py" = "manage.py:main"

[project.optional-dependencies]
dev = [
  "pip-tools",
  "black",
  "coverage",
]


[tool.setuptools]
packages = ['defects']
include-package-data = true

[tool.black]
target-version = ['py311']
line-length = 150

[tool.isort]
profile = "black"

[tool.coverage.run]
omit = [
  "*/migrations/*.py",
  "manage.py",
  "*/__init__.py",
]
