# Generated by Django 4.2.2 on 2023-06-21 10:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=200, unique=True)),
                ("operation", models.CharField(default="AMB", max_length=200)),
                ("area", models.CharField(blank=True, max_length=200)),
                ("time_start", models.DateTimeField(blank=True, null=True)),
                ("time_end", models.DateTimeField(blank=True, null=True)),
                ("significant", models.BooleanField(default=False)),
                ("short_description", models.CharField(blank=True, max_length=200)),
                ("long_description", models.TextField(blank=True)),
                ("ri_number", models.CharField(blank=True, max_length=200)),
                ("notification_time_received", models.DateTimeField(blank=True, null=True)),
                ("notification_am_reviewed", models.BooleanField(default=False)),
                ("notification_circulated", models.BooleanField(default=False)),
                ("notification_file", models.FileField(blank=True, upload_to="")),
                ("close_out_file", models.FileField(blank=True, upload_to="")),
                ("report_file", models.FileField(blank=True, upload_to="")),
                ("production_value_loss", models.DecimalField(blank=True, decimal_places=10, default=Decimal("0.00"), max_digits=20)),
                ("rand_value_loss", models.DecimalField(blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("possible_effect", models.TextField(blank=True)),
                ("immediate_action_taken", models.TextField(blank=True)),
                ("remaining_risk", models.TextField(blank=True)),
                ("equipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="defects.equipment")),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UserAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_required", models.DateTimeField(blank=True, null=True)),
                ("time_dismissed", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("incident", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="defects.incident")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reliability_incident_name", models.CharField(blank=True, max_length=500)),
                ("priority", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("person_responsible", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(blank=True, max_length=200)),
                ("planned_completion_date", models.DateField(blank=True, null=True)),
                ("planned_completion_date_string", models.CharField(blank=True, max_length=200)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date_string", models.CharField(blank=True, max_length=200)),
                ("incident_date_string", models.CharField(blank=True, max_length=200)),
                ("dr_number", models.CharField(blank=True, max_length=200)),
                ("remarks", models.TextField(blank=True)),
                ("area", models.CharField(blank=True, max_length=200)),
                ("incident", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="defects.incident")),
            ],
        ),
        migrations.CreateModel(
            name="SeniorAssetManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SectionEngineeringManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SectionEngineer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="incident",
            name="section",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidents", to="defects.section"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="section_engineer",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="defects.sectionengineer"),
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[("engineering_manager", "EM"), ("section_engineering_manager", "SEM"), ("senior_asset_manager", "Senior AM")],
                        max_length=200,
                    ),
                ),
                ("type", models.CharField(choices=[("notification", "Notification"), ("rca", "RCA")], max_length=100)),
                ("outcome", models.CharField(choices=[("accepted", "Accepted"), ("rejected", "Rejected")], max_length=100)),
                ("comment", models.TextField(blank=True)),
                ("incident", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="defects.incident")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
