# Generated by Django 4.1.3 on 2022-11-08 12:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReliabilityIncident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(blank=True, max_length=200)),
                ("section_engineer", models.CharField(max_length=200)),
                ("time_start", models.DateTimeField()),
                ("time_end", models.DateTimeField()),
                ("equipment", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ri_number", models.CharField(blank=True, max_length=200)),
                ("notification_time_received", models.DateTimeField(blank=True)),
                ("notification_am_reviewed", models.BooleanField(default=False)),
                ("notification_circulated", models.BooleanField(default=False)),
                ("notification_file", models.FileField(blank=True, upload_to="")),
                ("close_out_file", models.FileField(blank=True, upload_to="")),
                ("rca_file", models.FileField(blank=True, upload_to="")),
                ("report_file", models.FileField(blank=True, upload_to="")),
                ("production_value_loss", models.DecimalField(blank=True, decimal_places=10, default=Decimal("0.00"), max_digits=20)),
                ("rand_value_loss", models.DecimalField(blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("person_responsible", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(blank=True, max_length=200)),
                ("planned_completion_date", models.DateField(blank=True)),
                ("actual_completion_date", models.DateField(blank=True)),
                ("dr_number", models.CharField(blank=True, max_length=200)),
                ("remarks", models.TextField(blank=True)),
                (
                    "reliability_incident",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="defects.reliabilityincident"),
                ),
            ],
        ),
    ]
