# Generated by Django 4.1.3 on 2022-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="reliability_incident_name",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
