# Generated by Django 4.1.3 on 2022-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0002_solution_reliability_incident_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="actual_completion_date_string",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="solution",
            name="incident_date_string",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="solution",
            name="planned_completion_date_string",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
