# Generated by Django 4.2.2 on 2023-06-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0002_incident_created_by_incident_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="equipment",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidents", to="defects.equipment"
            ),
        ),
    ]
