# Generated by Django 4.1.3 on 2022-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0003_solution_actual_completion_date_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="actual_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solution",
            name="planned_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
