# Generated by Django 4.2.2 on 2023-06-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0003_alter_incident_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("ongoing", "Ongoing"),
                    ("complete", "Complete"),
                    ("overdue", "Overdue"),
                    ("incomplete", "Incomplete"),
                ],
                default="active",
                max_length=100,
            ),
        ),
    ]
