# Generated by Django 4.2.2 on 2023-07-21 11:04

import defects.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0004_incident_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "Equipment", "verbose_name_plural": "Equipment"},
        ),
        migrations.AlterModelOptions(
            name="incident",
            options={"verbose_name": "Incident", "verbose_name_plural": "Incidents"},
        ),
        migrations.RemoveField(
            model_name="incident",
            name="ri_number",
        ),
        migrations.AddField(
            model_name="incident",
            name="preliminary_findings",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
    ]
