# Generated by Django 4.1.3 on 2022-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_alter_solution_actual_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='area',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
