# Generated by Django 4.2.2 on 2023-07-21 11:45

import defects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("defects", "0005_alter_equipment_options_alter_incident_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.PositiveIntegerField(default=0, help_text="Change these values to alter ordering of images")),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="images", to="defects.incident"
                    ),
                ),
            ],
        ),
    ]
