# Generated by Django 4.1.3 on 2022-11-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0005_solution_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="reliabilityincident",
            name="mine",
            field=models.CharField(default="AMB", max_length=200),
        ),
        migrations.AddField(
            model_name="reliabilityincident",
            name="significant",
            field=models.BooleanField(default=False),
        ),
    ]
