# Generated by Django 4.2.2 on 2023-07-23 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0007_area_operation_alter_incident_area_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="notification_time_received",
            new_name="notification_time_published",
        ),
    ]
