# Generated by Django 4.1.3 on 2022-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0007_alter_reliabilityincident_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reliabilityincident",
            name="notification_time_received",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
