# Generated by Django 4.2.4 on 2023-08-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("defects", "0008_rename_notification_time_received_incident_notification_time_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sectionengineer",
            options={"verbose_name": "Section Engineer", "verbose_name_plural": "Section Engineers"},
        ),
        migrations.AlterModelOptions(
            name="sectionengineeringmanager",
            options={"verbose_name": "Section Engineering Manager", "verbose_name_plural": "Section Engineering Managers"},
        ),
        migrations.AlterField(
            model_name="approval",
            name="incident",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approvals", to="defects.incident"),
        ),
    ]
