# Generated by Django 4.1.3 on 2022-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0010_rename_mine_reliabilityincident_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reliabilityincident",
            name="area",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
