# Generated by Django 4.1.3 on 2022-12-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0011_reliabilityincident_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reliabilityincident',
            name='rca_file',
        ),
    ]
