# Generated by Django 4.2.4 on 2023-08-23 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0011_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="section_engineer",
        ),
    ]
