# Generated by Django 4.1.3 on 2022-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0012_remove_reliabilityincident_rca_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="reliabilityincident",
            name="immediate_action_taken",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reliabilityincident",
            name="possible_effect",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reliabilityincident",
            name="remaining_risk",
            field=models.TextField(blank=True),
        ),
    ]
