# Generated by Django 4.2.4 on 2023-08-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0013_incident_section_engineer_alter_incident_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="reliability_incident_name",
        ),
        migrations.AlterField(
            model_name="solution",
            name="incident",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="solutions", to="defects.incident"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("short_term", "Short Term"), ("medium_term", "Medium Term"), ("long_term", "Long Term")],
                default="short_term",
                max_length=200,
            ),
        ),
    ]
