# Generated by Django 4.2.4 on 2023-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0014_remove_solution_reliability_incident_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("identified", "Identified"), ("completed", "Complated"), ("scheduled", "Scheduled")],
                default="identified",
                max_length=200,
            ),
        ),
    ]
