# Generated by Django 4.2.4 on 2023-08-24 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0015_alter_solution_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seniorassetmanager",
            name="user",
        ),
        migrations.DeleteModel(
            name="SectionEngineer",
        ),
        migrations.DeleteModel(
            name="SeniorAssetManager",
        ),
    ]
