# Generated by Django 4.2.4 on 2023-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0017_approval_created_by_alter_approval_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="notification_am_reviewed",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="notification_circulated",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="notification_file",
        ),
        migrations.AlterField(
            model_name="incident",
            name="preliminary_findings",
            field=models.FileField(blank=True, default="", upload_to="files/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incident",
            name="report_file",
            field=models.FileField(blank=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("complete", "Complete"), ("overdue", "Overdue"), ("incomplete", "Incomplete")],
                default="active",
                max_length=100,
            ),
        ),
    ]
