# Generated by Django 4.2.4 on 2023-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0018_remove_incident_notification_am_reviewed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="notification_time_approved",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
