# Generated by Django 4.2.4 on 2023-08-27 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0019_incident_notification_time_approved"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAction",
        ),
    ]
