# Generated by Django 4.2.4 on 2023-08-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0020_delete_useraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("complete", "Complete"), ("overdue", "Overdue"), ("scheduled", "Scheduled")],
                default="active",
                max_length=100,
            ),
        ),
    ]
