# Generated by Django 4.2.4 on 2023-08-27 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0021_alter_incident_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SectionEngineeringManager",
        ),
    ]
