# Generated by Django 4.2.5 on 2023-09-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0022_delete_sectionengineeringmanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("repair", "Estimated cost of Repair > R 250K"),
                    ("production_loss", "Production Loss > 3 hours"),
                    ("shift_loss", "Loss of Full Production shift or Evacuation of shift"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="operation",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidents", to="defects.operation"
            ),
        ),
    ]
