# Generated by Django 4.2.5 on 2023-09-11 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0023_incident_trigger_alter_incident_operation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="possible_effect",
        ),
    ]
