# Generated by Django 4.2.5 on 2023-09-11 08:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0024_remove_incident_possible_effect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="production_value_loss",
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal("0.00"), max_digits=20),
        ),
    ]
