# Generated by Django 4.2.5 on 2023-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0025_alter_incident_production_value_loss"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="actual_completion_date_string",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="planned_completion_date_string",
        ),
        migrations.AddField(
            model_name="solution",
            name="timeframe",
            field=models.CharField(
                blank=True,
                choices=[("short_term", "Short Term"), ("medium_term", "Medium Term"), ("long_term", "Long Term")],
                default="short_term",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="priority",
            field=models.CharField(blank=True, choices=[("a", "A"), ("b", "B"), ("c", "C")], default="A", max_length=200),
        ),
        migrations.AlterField(
            model_name="solution",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("identified", "Identified"), ("completed", "Completed"), ("scheduled", "Scheduled")],
                default="identified",
                max_length=200,
            ),
        ),
    ]
