# Generated by Django 4.2.5 on 2023-09-12 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0026_remove_solution_actual_completion_date_string_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="incident_date_string",
        ),
    ]
