# Generated by Django 4.2.5 on 2023-09-12 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0027_remove_solution_incident_date_string"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="area",
        ),
    ]
