# Generated by Django 4.2.5 on 2023-09-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0028_remove_solution_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourcePrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
