# Generated by Django 4.2.6 on 2023-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0029_resourceprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="time_anniversary_reviewed",
            field=models.DateTimeField(blank=True, help_text="Records when the 1-year anniversary review was completed.", null=True),
        ),
        migrations.AlterField(
            model_name="resourceprice",
            name="rate",
            field=models.DecimalField(decimal_places=2, help_text="Price in ZAR of the resource per ounce.", max_digits=10),
        ),
    ]
