# Generated by Django 4.2.6 on 2023-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0030_incident_time_anniversary_reviewed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="time_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solution",
            name="verification_comment",
            field=models.TextField(blank=True),
        ),
    ]
