# Generated by Django 4.2.6 on 2024-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0031_solution_time_verified_solution_verification_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ["order_index"]},
        ),
        migrations.AlterModelOptions(
            name="operation",
            options={"ordering": ["order_index"]},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order_index"]},
        ),
        migrations.AddField(
            model_name="area",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="operation",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="section",
            name="order_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
