# Generated by Django 4.2.6 on 2024-03-06 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0032_alter_area_options_alter_operation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={
                "permissions": (("request_notification_approval", "Can request approval of incident notification"),),
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
            },
        ),
    ]
