# Generated by Django 4.2.6 on 2024-03-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0034_resourceprice_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="close_out_confidence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_downtime_repair_cost",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_immediate_cause",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_long_term_actions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_medium_term_actions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_root_cause",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_short_term_actions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="significant",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="solution",
            name="incident",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="solutions", to="defects.incident"
            ),
        ),
    ]
