# Generated by Django 4.2.6 on 2024-03-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0035_incident_close_out_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="close_out_long_term_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_medium_term_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_short_term_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
