# Generated by Django 4.2.6 on 2024-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0036_incident_close_out_long_term_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="score",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="incident",
            name="close_out_time_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approval",
            name="role",
            field=models.CharField(
                choices=[
                    ("section_engineer", "SE"),
                    ("engineering_manager", "EM"),
                    ("section_engineering_manager", "SEM"),
                    ("senior_asset_manager", "Senior AM"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="type",
            field=models.CharField(choices=[("notification", "Notification"), ("rca", "RCA"), ("close_out", "Close-Out")], max_length=100),
        ),
    ]
