# Generated by Django 4.2.6 on 2024-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0037_approval_score_incident_close_out_time_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="status",
        ),
        migrations.AddField(
            model_name="incident",
            name="rca_report_time_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
