# Generated by Django 4.2.6 on 2024-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0039_remove_incident_close_out_downtime_repair_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='time_verified',
        ),
        migrations.AddField(
            model_name='solution',
            name='date_verified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
