# Generated by Django 4.2.6 on 2024-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0040_remove_solution_time_verified_solution_date_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled')], default='scheduled', max_length=100),
        ),
    ]
