# Generated by Django 4.2.6 on 2024-03-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0042_incident_anniversary_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='rca_report_time_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
