# Generated by Django 4.2.6 on 2024-03-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0044_solution_created_by_solution_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='close_out_time_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
