# Generated by Django 5.0.4 on 2024-04-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0045_incident_close_out_time_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
