# Generated by Django 5.0.4 on 2024-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0046_section_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('short_term', 'Short-Term Actions (complete in 3 months)'), ('medium_term', 'Medium-Term Actions (complete in 3-6 months)'), ('long_term', 'Long-Term Actions (complete in 6-12 months)')], default='short_term', max_length=200),
        ),
    ]
