# Generated by Django 5.0.4 on 2024-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0047_alter_solution_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='close_out_rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
