# Generated by Django 5.0.4 on 2024-07-01 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0048_incident_close_out_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='incident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='defects.incident'),
        ),
    ]
