# Generated by Django 5.0.4 on 2024-07-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0049_alter_approval_created_by_alter_approval_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='defects.operation'),
        ),
        migrations.AddField(
            model_name='section',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='defects.area'),
        ),
    ]
