# Generated by Django 5.0.4 on 2024-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0050_area_operation_section_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='anniversary_success',
            field=models.BooleanField(default=False, help_text='Indicates whether the RI root cause was resolved'),
        ),
    ]
