# Generated by Django 5.1.1 on 2025-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0051_incident_anniversary_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
